---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{.NAME}}
        service: {{.NAME}}
    spec:
      containers:
        - name: {{.NAME}}
          image: quay.io/ukhomeofficedigital/acp-node-hello-world:v0.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 4000