---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.NAME}}
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/auth-tls-verify-client: "on"
    ingress.kubernetes.io/auth-tls-secret: "{{.KUBE_NAMESPACE}}/{{.NAME}}-auth"
    ingress.kubernetes.io/auth-tls-verify-depth: "3"



spec:
  rules:
    - host: {{.URL}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.NAME}}
              servicePort: http
  tls:
    - hosts:
      - {{.URL}}
      secretName: {{.NAME}}-TLS